version: "3"

services:
  ssh-tunnel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh-tunnel
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"
    user: "root"
    volumes:
      - ./vol/ssh:/home/sshonly/.ssh
    command: ["/bin/sh"]